### ISSUE TITLE
No addon settings shown for 3.6

### ISSUE THREAD

**Issue by vncastanheira** [azeemba/blender-add-outline#1]
Hello.
I'm trying to use this addon on Blender 3.6.5 and in the preferences it's being show as this.
Should it have a path or something?

![blender_mEv5hViDpB](https://github.com/azeemba/blender-add-outline/assets/1210284/a4a733e2-462a-4e91-b286-34e5ff2ecbab)

**Comment by azeemba** [comment]
Thanks for reporting this issue! I wasn't aware that Blender changed how settings were defined. I have tested the fix with Blender 4.0 but I expect it will work on 3.6 as well. 

Please let me know if it doesn't!
